Document: raptor-ica
Title: Debian raptor-ica Manual
Author: <insert document author here>
Abstract: This manual describes what raptor-ica is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/raptor-ica/raptor-ica.sgml.gz

Format: postscript
Files: /usr/share/doc/raptor-ica/raptor-ica.ps.gz

Format: text
Files: /usr/share/doc/raptor-ica/raptor-ica.text.gz

Format: HTML
Index: /usr/share/doc/raptor-ica/html/index.html
Files: /usr/share/doc/raptor-ica/html/*.html
